### PR TITLE
 Examples website revitalization blog post (take 3)

### PR DESCRIPTION
**Pull request by maximlt**
Replaces https://github.com/holoviz-dev/blog/pull/63 and https://github.com/holoviz-dev/blog/pull/64 to overcome a limitation with the infra of this repo, PRs from external contributors do not trigger a dev site build (not required but very handy to review).

### CODE REVIEW

**Comment by maximlt** [comment]
@jtao1 @Azaya89 in the blog post we're linking to your Github profiles. Let us know if you want us to link to another profile page instead (LinkedIn, X, etc.)!

**Comment by Azaya89** [comment]
> @jtao1 @Azaya89 in the blog post we're linking to your Github profiles. Let us know if you want us to link to another profile page instead (LinkedIn, X, etc.)!

My Github is fine.

**Comment by jtao1** [comment]
My github would be best!

**Comment by maximlt** [comment]
@droumis @Azaya89 @jtao1 this is finally ready for another round of review. I made some significant changes, I hope they went in the right direction. I also made us the 4 authors of the blog post, I thought that made sense given how we worked together on this project.

**Review by droumis — APPROVED** [review]

**Comment by maximlt** [comment]
Thanks all for your contributions, we made it! :)

**Pull request merged**
